// MAPEAMENTO_SIGLAS.ts
// Gerado a partir de NNM_YTD_1225.xlsx (aba de_para) + ajustes manuais
// Mapeia código de conta/custodiante → sigla do cliente na plataforma
// Adicionar novas entradas conforme novos clientes/contas forem criados

export const MAPEAMENTO_SIGLAS: Record<string, string> = {
  '157': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  '21526903902': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  '7206822': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ_BTG': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ_C': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ_GLPG': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ_ICATU': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ABJ_XP': 'ABJ',  // ADEMILSON BRAGA BISPO JUNIOR
  'ACM_BTG': 'ACM',  // ANA CAROLINA ARANTES MIGUEL
  'ACM_C': 'ACM',  // ANA CAROLINA ARANTES MIGUEL
  '7207206': 'AJF',  // ALAN JAVIER FRANCO
  'AJF': 'AJF',  // ALAN JAVIER FRANCO
  'AJF_C': 'AJF',  // ALAN JAVIER FRANCO
  'AJF_GLPG': 'AJF',  // ALAN JAVIER FRANCO
  'AKS': 'AKS',  // ALAN KARDEC
  'AKS_BTG': 'AKS',  // ALAN KARDEC
  'AKS_C': 'AKS',  // ALAN KARDEC
  'AKS_GLPG': 'AKS',  // ALAN KARDEC
  '8206874': 'AMI',  // AMILCAR AUGUSTO LOPES JUNIOR
  'AMI_C': 'AMI',  // AMILCAR AUGUSTO LOPES JUNIOR
  'AMI_GLPG': 'AMI',  // AMILCAR AUGUSTO LOPES JUNIOR
  'ARM': 'ARM',  // ARTHUR MENDONÇA CABRAL
  'ARM_BTG': 'ARM',  // ARTHUR MENDONÇA CABRAL
  'ARM_C': 'ARM',  // ARTHUR MENDONÇA CABRAL
  'ARM_GLPG': 'ARM',  // ARTHUR MENDONÇA CABRAL
  'ARM_ICATU': 'ARM',  // ARTHUR MENDONÇA CABRAL
  'ARM_XP': 'ARM',  // ARTHUR MENDONÇA CABRAL
  '7207590': 'ARV',  // ANA RAQUEL VICTOR GUIMARAES
  'ARV': 'ARV',  // ANA RAQUEL VICTOR GUIMARAES
  'ARV_BTG': 'ARV',  // ANA RAQUEL VICTOR GUIMARAES
  'ARV_C': 'ARV',  // ANA RAQUEL VICTOR GUIMARAES
  'ARV_XP': 'ARV',  // ANA RAQUEL VICTOR GUIMARAES
  '41659514198': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG_BTG': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG_C': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG_GLPG': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG_ICATU': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'AVG_XP': 'AVG',  // ARTUR VICTOR GUIMARÃES
  'BBM_C': 'BBM',  // BARBARA BARLETTA MACHADO DA SILVA
  'BBM_GLPG': 'BBM',  // BARBARA BARLETTA MACHADO DA SILVA
  'CLB_C': 'CLB',  // CAUAN LUCAS BARROS DA LUZ
  'CLB_GLPG': 'CLB',  // CAUAN LUCAS BARROS DA LUZ
  'CSP_C': 'CSP',  // CARLOS EDUARDO FIRACE SCAPPINI
  'CSP_GLPG': 'CSP',  // CARLOS EDUARDO FIRACE SCAPPINI
  'CSP_XP': 'CSP',  // CARLOS EDUARDO FIRACE SCAPPINI
  '7207435': 'CSR',  // CASSIO RAMOS
  'CSR': 'CSR',  // CASSIO RAMOS
  'CSR_C': 'CSR',  // CASSIO RAMOS
  'CSR_GLPG': 'CSR',  // CASSIO RAMOS
  'CSR_ICATU': 'CSR',  // CASSIO RAMOS
  'CSR_XP': 'CSR',  // CASSIO RAMOS
  'DGS': 'DGS',  // DIEGO GABRIEL DA SILVA ROSA
  'DGS_BTG': 'DGS',  // DIEGO GABRIEL DA SILVA ROSA
  'DGS_C': 'DGS',  // DIEGO GABRIEL DA SILVA ROSA
  'DGS_ICATU': 'DGS',  // DIEGO GABRIEL DA SILVA ROSA
  'DJA': 'DJA',  // DJAMILA RIBEIRO
  'DJA_BTG': 'DJA',  // DJAMILA RIBEIRO
  'DJA_C': 'DJA',  // DJAMILA RIBEIRO
  'DJA_GLPG': 'DJA',  // DJAMILA RIBEIRO
  'DSJ_BTG': 'DSJ',  // DEJANE SILVA SANTANA
  'DSJ_C': 'DSJ',  // DEJANE SILVA SANTANA
  '7206821': 'DSS',  // DANIEL SAMPAIO SIMOES
  'DSS': 'DSS',  // DANIEL SAMPAIO SIMOES
  'DSS_C': 'DSS',  // DANIEL SAMPAIO SIMOES
  'DSS_GLPG': 'DSS',  // DANIEL SAMPAIO SIMOES
  'DSS_ICATU': 'DSS',  // DANIEL SAMPAIO SIMOES
  'DSS_XP': 'DSS',  // DANIEL SAMPAIO SIMOES
  'EMT_BTG': 'EMT',  // EMILIANO MARTINEZ TORANZA
  'EMT_C': 'EMT',  // EMILIANO MARTINEZ TORANZA
  '7206778': 'ESR',  // ERIC DOS SANTOS RODRIGUES
  'ESR': 'ESR',  // ERIC DOS SANTOS RODRIGUES
  'ESR_C': 'ESR',  // ERIC DOS SANTOS RODRIGUES
  'ESR_GLPG': 'ESR',  // ERIC DOS SANTOS RODRIGUES
  'ESR_XP': 'ESR',  // ERIC DOS SANTOS RODRIGUES
  '147': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  '20695261280': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  '236': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  '7206556': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  'FAV': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  'FAV_C': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  'FAV_GLPG': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  'FAV_XP': 'FAV',  // MARCO ANTONIO FAVA FIALDINI
  'FNR': 'FNR',  // FUNDAÇÃO FENÔMENOS
  'FNR_C': 'FNR',  // FUNDAÇÃO FENÔMENOS
  'FNR_BTG': 'FNR',  // FUNDAÇÃO FENÔMENOS
  'FSP_C': 'FSP',  // FLORENCE ANDRADE GUIMARAES SCAPPINI
  'FSP_GLPG': 'FSP',  // FLORENCE ANDRADE GUIMARAES SCAPPINI
  'FSP_XP': 'FSP',  // FLORENCE ANDRADE GUIMARAES SCAPPINI
  '27900359186': 'GABRIEL JESUS',  // GABRIEL FERNANDO DE JESUS
  '37180302883': 'GABRIEL JESUS',  // GABRIEL FERNANDO DE JESUS
  'GABRIEL JESUS_C': 'GABRIEL JESUS',  // GABRIEL FERNANDO DE JESUS
  '8207156': 'GABRIEL PIPINO',  // GABRIEL PIPINO
  'GABRIEL PIPINO_C': 'GABRIEL PIPINO',  // GABRIEL PIPINO
  '7207234': 'GLP',  // GABRIEL NATHAN SILVA FERNANDES
  'GLP': 'GLP',  // GABRIEL NATHAN SILVA FERNANDES
  'GLP_C': 'GLP',  // GABRIEL NATHAN SILVA FERNANDES
  'GLP_GLPG': 'GLP',  // GABRIEL NATHAN SILVA FERNANDES
  '207061': 'GMD',  // GABRIEL MARCATTO BENETTON
  '7207061': 'GMD',  // GABRIEL MARCATTO BENETTON
  'GMB': 'GMD',  // GABRIEL MARCATTO BENETTON
  'GMB_BTG': 'GMD',  // GABRIEL MARCATTO BENETTON
  'GMB_GLPG': 'GMD',  // GABRIEL MARCATTO BENETTON
  'GMD_C': 'GMD',  // GABRIEL MARCATTO BENETTON
  'GMS_BTG': 'GMS',  // GREGORE DE MAGALHAES SILVA FAVERO
  'GMS_C': 'GMS',  // GREGORE DE MAGALHAES SILVA FAVERO
  'GNG': 'GNG',  // GUSTAVO NUNES FERNANDES GOMES
  'GNG_BTG': 'GNG',  // GUSTAVO NUNES FERNANDES GOMES
  'GNG_C': 'GNG',  // GUSTAVO NUNES FERNANDES GOMES
  'GNG_ICATU': 'GNG',  // GUSTAVO NUNES FERNANDES GOMES
  '158': 'GPS',  // GABRIEL PEREIRA DOS SANTOS
  '20695302047': 'GPS',  // GABRIEL PEREIRA DOS SANTOS
  'GPS': 'GPS',  // GABRIEL PEREIRA DOS SANTOS
  'GPS_C': 'GPS',  // GABRIEL PEREIRA DOS SANTOS
  'HDE': 'HDE',  // HARIEL DENARO RIBEIRO
  'HDE_C': 'HDE',  // HARIEL DENARO RIBEIRO
  'HDE_GLPG': 'HDE',  // HARIEL DENARO RIBEIRO
  'HDE_ICATU': 'HDE',  // HARIEL DENARO RIBEIRO
  'JCS_C': 'JCS',  // JOÃO CARLOS SOLER DIAGO
  'JCS_GLPG': 'JCS',  // JOÃO CARLOS SOLER DIAGO
  'JFE': 'JFE',  // JOAO FELIPE SCHMIDT URBANO
  'JFE_BTG': 'JFE',  // JOAO FELIPE SCHMIDT URBANO
  'JFE_C': 'JFE',  // JOAO FELIPE SCHMIDT URBANO
  'JFE_GLPG': 'JFE',  // JOAO FELIPE SCHMIDT URBANO
  'JFF': 'JFF',  // JEAN PAULO FERNANDES FILHO
  'JFF_BTG': 'JFF',  // JEAN PAULO FERNANDES FILHO
  'JFF_C': 'JFF',  // JEAN PAULO FERNANDES FILHO
  '7206977': 'JLM',  // JOSE CARLOS LOPES DE MACEDO
  'JLM': 'JLM',  // JOSE CARLOS LOPES DE MACEDO
  'JLM_C': 'JLM',  // JOSE CARLOS LOPES DE MACEDO
  'JLM_GLPG': 'JLM',  // JOSE CARLOS LOPES DE MACEDO
  'JLM_ICATU': 'JLM',  // JOSE CARLOS LOPES DE MACEDO
  '36609548715': 'JVC',  // JOÃO VICTOR ANDRADE CAETANO
  'JVC': 'JVC',  // JOÃO VICTOR ANDRADE CAETANO
  'JVC_C': 'JVC',  // JOÃO VICTOR ANDRADE CAETANO
  'JVC_GLPG': 'JVC',  // JOÃO VICTOR ANDRADE CAETANO
  'JVC_XP': 'JVC',  // JOÃO VICTOR ANDRADE CAETANO
  '7206792': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI_BTG': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI_C': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI_GLPG': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI_ICATU': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'JVI_XP': 'JVI',  // JOÃO VICTOR DA SILVA MARCELINO
  'KSL': 'KSL',  // KEVIN SANTOS LOPES
  'KSL_BTG': 'KSL',  // KEVIN SANTOS LOPES
  'KSL_C': 'KSL',  // KEVIN SANTOS LOPES
  'KSL_GLPG': 'KSL',  // KEVIN SANTOS LOPES
  '18017269175': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '32': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '4749109': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '4758282': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '7193704': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '8201615': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  'LAG': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  'LAG_C': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  'LAG_GLPG': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  'LAG_ICATU': 'LAG',  // LUIZ DE ARAUJO GUIMARAES NETO
  '7206966': 'LEJ',  // LEONARDO CESAR JARDIM
  'LEJ': 'LEJ',  // LEONARDO CESAR JARDIM
  'LEJ_C': 'LEJ',  // LEONARDO CESAR JARDIM
  'LEJ_GLPG': 'LEJ',  // LEONARDO CESAR JARDIM
  'LEJ_ICATU': 'LEJ',  // LEONARDO CESAR JARDIM
  'LEJ_XP': 'LEJ',  // LEONARDO CESAR JARDIM
  '7207592': 'LES',  // LUCAS ESTEVES SOUZA
  'LES': 'LES',  // LUCAS ESTEVES SOUZA
  'LES_C': 'LES',  // LUCAS ESTEVES SOUZA
  'LES_GLPG': 'LES',  // LUCAS ESTEVES SOUZA
  'LES_XP': 'LES',  // LUCAS ESTEVES SOUZA
  'LEV': 'LEV',  // LUCAS EVANGELISTA
  'LEV_BTG': 'LEV',  // LUCAS EVANGELISTA
  'LEV_C': 'LEV',  // LUCAS EVANGELISTA
  'LEV_GLPG': 'LEV',  // LUCAS EVANGELISTA
  '252': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  '33900730477': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  '37186887518': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LGJ': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LGJ_BTG': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LGJ_C': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LGJ_GLPG': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LGJ_SP': 'LGJ',  // LUAN GUILHERME DE JESUS VIEIRA
  'LHA': 'LHA',  // LUIZ HENRIQUE ANDRE ROSA DA SILVA
  'LHA_BTG': 'LHA',  // LUIZ HENRIQUE ANDRE ROSA DA SILVA
  'LHA_C': 'LHA',  // LUIZ HENRIQUE ANDRE ROSA DA SILVA
  'LHA_XP': 'LHA',  // LUIZ HENRIQUE ANDRE ROSA DA SILVA
  '7207072': 'LIS',  // LORENA IMPROTA NUNES SANTANA
  'LIS': 'LIS',  // LORENA IMPROTA NUNES SANTANA
  'LIS_BTG': 'LIS',  // LORENA IMPROTA NUNES SANTANA
  'LIS_C': 'LIS',  // LORENA IMPROTA NUNES SANTANA
  'LIS_GLPG': 'LIS',  // LORENA IMPROTA NUNES SANTANA
  'LRR_BTG': 'LRR',  // LUCIANO RODRIGUEZ ROSALES
  'LRR_C': 'LRR',  // LUCIANO RODRIGUEZ ROSALES
  'LSI': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  'LSI_BP': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  'LSI_BTG': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  'LSI_C': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  'LSI_GLPG': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  'LSI_SICREDI': 'LSI',  // LEANDRO SILVA DE SANTANA IMPROTA
  '266': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  '35810866230': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  '7206783': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MAY': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MAY_BTG': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MAY_C': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MAY_GLPG': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MAY_XP': 'MAY',  // MAYCON VINICIUS FERREIRA DA CRUZ
  'MBS': 'MBS',  // MATHEUS BONIFACIO SALDANHA
  'MBS_BTG': 'MBS',  // MATHEUS BONIFACIO SALDANHA
  'MBS_C': 'MBS',  // MATHEUS BONIFACIO SALDANHA
  '267': 'MIS',  // MATHEUS ISAIAS DOS SANTOS
  '36814819482': 'MIS',  // MATHEUS ISAIAS DOS SANTOS
  'MIS_BTG': 'MIS',  // MATHEUS ISAIAS DOS SANTOS
  'MIS_C': 'MIS',  // MATHEUS ISAIAS DOS SANTOS
  'MIS_ICATU': 'MIS',  // MATHEUS ISAIAS DOS SANTOS
  '7207449': 'MJM',  // MAURICIO JOSE MACHADO FARIAS
  'MJM': 'MJM',  // MAURICIO JOSE MACHADO FARIAS
  'MJM_C': 'MJM',  // MAURICIO JOSE MACHADO FARIAS
  'MJM_GLPG': 'MJM',  // MAURICIO JOSE MACHADO FARIAS
  '33990756955': 'MLM',  // MOISES LIMA MAGALHAES
  '7206782': 'MLM',  // MOISES LIMA MAGALHAES
  'MLM': 'MLM',  // MOISES LIMA MAGALHAES
  'MLM_BTG': 'MLM',  // MOISES LIMA MAGALHAES
  'MLM_C': 'MLM',  // MOISES LIMA MAGALHAES
  'MLM_GLPG': 'MLM',  // MOISES LIMA MAGALHAES
  'MLM_XP': 'MLM',  // MOISES LIMA MAGALHAES
  'TAW019408': 'MLM',  // MOISES LIMA MAGALHAES — conta offshore Andbanc (MSAL)
  'D47226006': 'MLM',  // MOISES LIMA MAGALHAES — conta offshore JP Morgan (MSAL)
  '7207436': 'MRT',  // MATHEUS ROSSETTO
  'MRT': 'MRT',  // MATHEUS ROSSETTO
  'MRT_C': 'MRT',  // MATHEUS ROSSETTO
  'MRT_GLPG': 'MRT',  // MATHEUS ROSSETTO
  '7206791': 'MTS',  // MATHEUS BAHIA SANTOS
  'MTS': 'MTS',  // MATHEUS BAHIA SANTOS
  'MTS_C': 'MTS',  // MATHEUS BAHIA SANTOS
  'MTS_GLPG': 'MTS',  // MATHEUS BAHIA SANTOS
  'MTS_ICATU': 'MTS',  // MATHEUS BAHIA SANTOS
  '7206905': 'PCD',  // PAULA CAROLINE DE OLIVEIRA DANTAS
  'PCD': 'PCD',  // PAULA CAROLINE DE OLIVEIRA DANTAS
  'PCD_C': 'PCD',  // PAULA CAROLINE DE OLIVEIRA DANTAS
  'PCD_XP': 'PCD',  // PAULA CAROLINE DE OLIVEIRA DANTAS
  '7207292': 'PHB',  // PEDRO HENRIQUE DE ALMEIDA BARBOSA
  'PHB': 'PHB',  // PEDRO HENRIQUE DE ALMEIDA BARBOSA
  'PHB_BTG': 'PHB',  // PEDRO HENRIQUE DE ALMEIDA BARBOSA
  'PHB_C': 'PHB',  // PEDRO HENRIQUE DE ALMEIDA BARBOSA
  'PHB_ICATU': 'PHB',  // PEDRO HENRIQUE DE ALMEIDA BARBOSA
  '7206993': 'PLO',  // PATRICK DE LUCCA CHAVES DE OLIVEIRA
  'PLO': 'PLO',  // PATRICK DE LUCCA CHAVES DE OLIVEIRA
  'PLO_C': 'PLO',  // PATRICK DE LUCCA CHAVES DE OLIVEIRA
  'PLO_GLPG': 'PLO',  // PATRICK DE LUCCA CHAVES DE OLIVEIRA
  'PSS_BTG': 'PSS',  // PEDRO HENRIQUE SILVA DOS SANTOS
  'PSS_C': 'PSS',  // PEDRO HENRIQUE SILVA DOS SANTOS
  'PSS_ICATU': 'PSS',  // PEDRO HENRIQUE SILVA DOS SANTOS
  'PVI': 'PVI',  // PAULO VICTOR DE ALMEIDA BARBOSA
  'PVI_BTG': 'PVI',  // PAULO VICTOR DE ALMEIDA BARBOSA
  'PVI_C': 'PVI',  // PAULO VICTOR DE ALMEIDA BARBOSA
  'PVI_ICATU': 'PVI',  // PAULO VICTOR DE ALMEIDA BARBOSA
  '7207640': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RAI': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RAI_BTG': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RAI_C': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RAI_GLPG': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RAI_XP': 'RAI',  // RAIMUNDO VICTOR SOBRINHO
  'RDN': 'RDN',  // RONALD DOMINGUES NAZARIO DE LIMA
  'RDN_C': 'RDN',  // RONALD DOMINGUES NAZARIO DE LIMA
  'RDN_GLPG': 'RDN',  // RONALD DOMINGUES NAZARIO DE LIMA
  '146': 'RII',  // RAFAEL SILVA
  '20695260801': 'RII',  // RAFAEL SILVA
  'RII_C': 'RII',  // RAFAEL SILVA
  '255': 'RKG',  // ROGER KRUG GUEDES
  '33398081634': 'RKG',  // ROGER KRUG GUEDES
  'RKG': 'RKG',  // ROGER KRUG GUEDES
  'RKG_BTG': 'RKG',  // ROGER KRUG GUEDES
  'RKG_C': 'RKG',  // ROGER KRUG GUEDES
  'RKG_XP': 'RKG',  // ROGER KRUG GUEDES
  '7206116': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  'RLN': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  'RLN_BTG': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  'RLN_C': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  'RLN_GLPG': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  'RLN_ICATU': 'RLN',  // RONALDO LUIS NAZARIO DE LIMA
  '7206967': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  'SCS': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  'SCS_BTG': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  'SCS_C': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  'SCS_ICATU': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  'SCS_XP': 'SCS',  // SAMIR CAETANO DE SOUZA SANTOS
  '7206780': 'SMM',  // SONIA MARA DA SILVA MAGALHAES
  'SMM': 'SMM',  // SONIA MARA DA SILVA MAGALHAES
  'SMM_C': 'SMM',  // SONIA MARA DA SILVA MAGALHAES
  'SMM_GLPG': 'SMM',  // SONIA MARA DA SILVA MAGALHAES
  'SMM_XP': 'SMM',  // SONIA MARA DA SILVA MAGALHAES
  'STE': 'STE',  // STEFANY FERNANDES DOS SANTOS ABREU
  'STE_C': 'STE',  // STEFANY FERNANDES DOS SANTOS ABREU
  'STE_GLPG': 'STE',  // STEFANY FERNANDES DOS SANTOS ABREU
  'TCG': 'TCG',  // TAMIRES CÁSSIA DIAS DE BRITTO
  'TCG_BTG': 'TCG',  // TAMIRES CÁSSIA DIAS DE BRITTO
  'TCG_C': 'TCG',  // TAMIRES CÁSSIA DIAS DE BRITTO
  'TCG_GLPG': 'TCG',  // TAMIRES CÁSSIA DIAS DE BRITTO
  'TME': 'TME',  // THIAGO HENRIQUE SANTOS MENDES
  'TME_BTG': 'TME',  // THIAGO HENRIQUE SANTOS MENDES
  'TME_C': 'TME',  // THIAGO HENRIQUE SANTOS MENDES
  'TME_GLPG': 'TME',  // THIAGO HENRIQUE SANTOS MENDES
  'TME_ICATU': 'TME',  // THIAGO HENRIQUE SANTOS MENDES
  '207630': 'TMO',  // TIAGO MACHADO DE OLIVEIRA
  '7207630': 'TMO',  // TIAGO MACHADO DE OLIVEIRA
  'TMO_C': 'TMO',  // TIAGO MACHADO DE OLIVEIRA
  'TMO_GLPG': 'TMO',  // TIAGO MACHADO DE OLIVEIRA
  '154': 'VIA',  // VICTOR ALEXANDER DA SILVA
  '20695302271': 'VIA',  // VICTOR ALEXANDER DA SILVA
  '257': 'VIA',  // VICTOR ALEXANDER DA SILVA
  '7207199': 'VIA',  // VICTOR ALEXANDER DA SILVA
  'VIA': 'VIA',  // VICTOR ALEXANDER DA SILVA
  'VIA_BTG': 'VIA',  // VICTOR ALEXANDER DA SILVA
  'VIA_C': 'VIA',  // VICTOR ALEXANDER DA SILVA
  'VIA_GLPG': 'VIA',  // VICTOR ALEXANDER DA SILVA
  '7207591': 'VLC',  // VIVIANE LEAL DA COSTA BARROS FREITAS
  'VLC_C': 'VLC',  // VIVIANE LEAL DA COSTA BARROS FREITAS
  'VLC_GLPG': 'VLC',  // VIVIANE LEAL DA COSTA BARROS FREITAS
  'WCB': 'WCB',  // WILLIAM DA CONCEICAO BENTO
  'WCB_C': 'WCB',  // WILLIAM DA CONCEICAO BENTO
  'WCB_GLPG': 'WCB',  // WILLIAM DA CONCEICAO BENTO
  '34489599498': 'WGC',  // WILLIAM GOMES CARVALHO SANTOS
  'WGC_BTG': 'WGC',  // WILLIAM GOMES CARVALHO SANTOS
  'WGC_C': 'WGC',  // WILLIAM GOMES CARVALHO SANTOS
  'WGC_ICATU': 'WGC',  // WILLIAM GOMES CARVALHO SANTOS
  'WRG_BTG': 'WRG',  // WENDERSON GALENO
  'WRG_C': 'WRG',  // WENDERSON GALENO
  'WRG_SP': 'WRG',  // WENDERSON GALENO
  '148': 'WRS',  // WESLEY RIBEIRO DA SILVA
  '20695262069': 'WRS',  // WESLEY RIBEIRO DA SILVA
  '7206775': 'WRS',  // WESLEY RIBEIRO DA SILVA
  'WRS': 'WRS',  // WESLEY RIBEIRO DA SILVA
  'WRS_BTG': 'WRS',  // WESLEY RIBEIRO DA SILVA
  'WRS_C': 'WRS',  // WESLEY RIBEIRO DA SILVA
  'WRS_GLPG': 'WRS',  // WESLEY RIBEIRO DA SILVA
  'WRS_XP': 'WRS',  // WESLEY RIBEIRO DA SILVA

  // ── Nomes offshore (US Performance Report) ─────────────────────────────
  // Nomes completos que aparecem no relatório offshore do Galápagos e
  // precisam ser resolvidos para a sigla do cliente onshore correspondente.
  // Holdings e SPVs primeiro, depois pessoas físicas (ordem alfabética).
  'LAG International Investments Ltd.': 'LAG',   // LUIZ DE ARAUJO GUIMARAES NETO
  'MSAL Investments Ltd.': 'MLM',                // MOISES LIMA MAGALHAES
  'RS Services Ltd.': 'RSS',                     // RAFAEL SILVA
  'Tomé Capital Group Ltd.': 'AVG',              // ARTUR VICTOR GUIMARÃES
  'Ademilson Braga Bispo Junior': 'ABJ',          // ADEMILSON BRAGA BISPO JUNIOR
  'Gabriel Fernando de Jesus': 'GFJ',            // GABRIEL FERNANDO DE JESUS (novo)
  'Gabriel Pereira Dos Santos': 'GPS',           // GABRIEL PEREIRA DOS SANTOS
  'João Victor Andrade Caetano': 'JVI',          // JOÃO VICTOR DA SILVA MARCELINO
  'Luan Guilherme de Jesus Vieira': 'LGJ',       // LUAN GUILHERME DE JESUS VIEIRA
  'Marco Antonio Fava Fialdini': 'FAV',          // MARCO ANTONIO FAVA FIALDINI
  'Matheus Isaias dos Santos': 'MTS',            // MATHEUS BAHIA SANTOS
  'Maycon Vinicius Ferreira da Cruz': 'MAY',     // MAYCON VINICIUS FERREIRA DA CRUZ
  'Oliver Decesary Santos': 'LIV',               // OLIVER DECESARY SANTOS (novo)
  'Roger Krug Guedes': 'RKG',                    // ROGER KRUG GUEDES
  'Victor Alexander da Silva': 'VIA',            // VICTOR ALEXANDER DA SILVA
  'Wenderson Galeno': 'WRG',                    // WENDERSON GALENO
  'Wesley Ribeiro Da Silva': 'WRS',              // WESLEY RIBEIRO DA SILVA
  'William Gomes Carvalho Santos': 'WGC',        // WILLIAM GOMES CARVALHO SANTOS
};

// Mapeamento inverso: sigla → nome completo (extraído dos comentários acima)
export const SIGLA_PARA_NOME: Record<string, string> = {
  'ABJ': 'ADEMILSON BRAGA BISPO JUNIOR',
  'ACM': 'ANA CAROLINA ARANTES MIGUEL',
  'AJF': 'ALAN JAVIER FRANCO',
  'AKS': 'ALAN KARDEC',
  'AMI': 'AMILCAR AUGUSTO LOPES JUNIOR',
  'ARM': 'ARTHUR MENDONÇA CABRAL',
  'ARV': 'ANA RAQUEL VICTOR GUIMARAES',
  'AVG': 'ARTUR VICTOR GUIMARÃES',
  'BBM': 'BARBARA BARLETTA MACHADO DA SILVA',
  'CLB': 'CAUAN LUCAS BARROS DA LUZ',
  'CSP': 'CARLOS EDUARDO FIRACE SCAPPINI',
  'CSR': 'CASSIO RAMOS',
  'DGS': 'DIEGO GABRIEL DA SILVA ROSA',
  'DJA': 'DJAMILA RIBEIRO',
  'DSJ': 'DEJANE SILVA SANTANA',
  'DSS': 'DANIEL SAMPAIO SIMOES',
  'EMT': 'EMILIANO MARTINEZ TORANZA',
  'ESR': 'ERIC DOS SANTOS RODRIGUES',
  'FAV': 'MARCO ANTONIO FAVA FIALDINI',
  'FNR': 'FUNDAÇÃO FENÔMENOS',
  'FSP': 'FLORENCE ANDRADE GUIMARAES SCAPPINI',
  'GABRIEL JESUS': 'GABRIEL FERNANDO DE JESUS',
  'GABRIEL PIPINO': 'GABRIEL PIPINO',
  'GFJ': 'GABRIEL FERNANDO DE JESUS',
  'GLP': 'GABRIEL NATHAN SILVA FERNANDES',
  'GMD': 'GABRIEL MARCATTO BENETTON',
  'GMS': 'GREGORE DE MAGALHAES SILVA FAVERO',
  'GNG': 'GUSTAVO NUNES FERNANDES GOMES',
  'GPS': 'GABRIEL PEREIRA DOS SANTOS',
  'HDE': 'HARIEL DENARO RIBEIRO',
  'JCS': 'JOÃO CARLOS SOLER DIAGO',
  'JFE': 'JOAO FELIPE SCHMIDT URBANO',
  'JFF': 'JEAN PAULO FERNANDES FILHO',
  'JLM': 'JOSE CARLOS LOPES DE MACEDO',
  'JVC': 'JOÃO VICTOR ANDRADE CAETANO',
  'JVI': 'JOÃO VICTOR DA SILVA MARCELINO',
  'KSL': 'KEVIN SANTOS LOPES',
  'LAG': 'LUIZ DE ARAUJO GUIMARAES NETO',
  'LEJ': 'LEONARDO CESAR JARDIM',
  'LES': 'LUCAS ESTEVES SOUZA',
  'LEV': 'LUCAS EVANGELISTA',
  'LIV': 'OLIVER DECESARY SANTOS',
  'LGJ': 'LUAN GUILHERME DE JESUS VIEIRA',
  'LHA': 'LUIZ HENRIQUE ANDRE ROSA DA SILVA',
  'LIS': 'LORENA IMPROTA NUNES SANTANA',
  'LRR': 'LUCIANO RODRIGUEZ ROSALES',
  'LSI': 'LEANDRO SILVA DE SANTANA IMPROTA',
  'MAY': 'MAYCON VINICIUS FERREIRA DA CRUZ',
  'MBS': 'MATHEUS BONIFACIO SALDANHA',
  'MIS': 'MATHEUS ISAIAS DOS SANTOS',
  'MJM': 'MAURICIO JOSE MACHADO FARIAS',
  'MLM': 'MOISES LIMA MAGALHAES',
  'MRT': 'MATHEUS ROSSETTO',
  'MTS': 'MATHEUS BAHIA SANTOS',
  'PCD': 'PAULA CAROLINE DE OLIVEIRA DANTAS',
  'PHB': 'PEDRO HENRIQUE DE ALMEIDA BARBOSA',
  'PLO': 'PATRICK DE LUCCA CHAVES DE OLIVEIRA',
  'PSS': 'PEDRO HENRIQUE SILVA DOS SANTOS',
  'PVI': 'PAULO VICTOR DE ALMEIDA BARBOSA',
  'RAI': 'RAIMUNDO VICTOR SOBRINHO',
  'RDN': 'RONALD DOMINGUES NAZARIO DE LIMA',
  'RII': 'RAFAEL SILVA',
  'RSS': 'RAFAEL SILVA',
  'RKG': 'ROGER KRUG GUEDES',
  'RLN': 'RONALDO LUIS NAZARIO DE LIMA',
  'SCS': 'SAMIR CAETANO DE SOUZA SANTOS',
  'SMM': 'SONIA MARA DA SILVA MAGALHAES',
  'STE': 'STEFANY FERNANDES DOS SANTOS ABREU',
  'TCG': 'TAMIRES CÁSSIA DIAS DE BRITTO',
  'TME': 'THIAGO HENRIQUE SANTOS MENDES',
  'TMO': 'TIAGO MACHADO DE OLIVEIRA',
  'VIA': 'VICTOR ALEXANDER DA SILVA',
  'VLC': 'VIVIANE LEAL DA COSTA BARROS FREITAS',
  'WCB': 'WILLIAM DA CONCEICAO BENTO',
  'WGC': 'WILLIAM GOMES CARVALHO SANTOS',
  'WRG': 'WENDERSON GALENO',
  'WRS': 'WESLEY RIBEIRO DA SILVA',
};

// Normaliza o código antes de buscar:
// - converte para maiúsculas
// - remove espaços extras
// Isso garante que variações como rkg_c ou "RKG_C " resolvam igual
export function resolverSigla(codigo: string): string | null {
  const normalizado = codigo.trim().toUpperCase();
  return MAPEAMENTO_SIGLAS[normalizado] ?? null;
}

// Inverso: nome completo → sigla curta (derivado de SIGLA_PARA_NOME)
export const NOME_PARA_SIGLA: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [sigla, nome] of Object.entries(SIGLA_PARA_NOME)) {
    // Pula entradas onde a sigla é o próprio nome (ex: "GABRIEL JESUS") — não há ganho visual
    if (sigla.trim().toUpperCase() === nome.trim().toUpperCase()) continue;
    out[nome.trim().toUpperCase()] = sigla;
  }
  return out;
})();

export function siglaPorNome(nome: string): string | null {
  if (!nome) return null;
  return NOME_PARA_SIGLA[nome.trim().toUpperCase()] ?? null;
}
